package wsPanFinder;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * wsEstablishments service = new wsEstablishments();
 * WsEstablishmentsSoap portType = service.getWsEstablishmentsSoap();
 * portType.getEstablishments(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "wsEstablishments", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://servicios.adsef.pr.gov/sdec_ws/wsEstablishments.asmx?WSDL")
public class WsEstablishments extends Service {

	private final static URL WSESTABLISHMENTS_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(wsPanFinder.WsEstablishments.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = wsPanFinder.WsEstablishments.class.getResource(".");
			url = new URL(baseUrl,
					"https://servicios.adsef.pr.gov/sdec_ws/wsEstablishments.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'https://servicios.adsef.pr.gov/sdec_ws/wsEstablishments.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSESTABLISHMENTS_WSDL_LOCATION = url;
	}

	public WsEstablishments(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WsEstablishments() {
		super(WSESTABLISHMENTS_WSDL_LOCATION, new QName("http://tempuri.org/",
				"wsEstablishments"));
	}

	/**
	 * 
	 * @return returns WsEstablishmentsSoap
	 */
	@WebEndpoint(name = "wsEstablishmentsSoap")
	public WsEstablishmentsSoap getWsEstablishmentsSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"wsEstablishmentsSoap"), WsEstablishmentsSoap.class);
	}

	/**
	 * 
	 * @return returns WsEstablishmentsSoap
	 */
	@WebEndpoint(name = "wsEstablishmentsSoap12")
	public WsEstablishmentsSoap getWsEstablishmentsSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"wsEstablishmentsSoap12"), WsEstablishmentsSoap.class);
	}

	/**
	 * 
	 * @return returns WsEstablishmentsHttpGet
	 */
	@WebEndpoint(name = "wsEstablishmentsHttpGet")
	public WsEstablishmentsHttpGet getWsEstablishmentsHttpGet() {
		return super.getPort(new QName("http://tempuri.org/",
				"wsEstablishmentsHttpGet"), WsEstablishmentsHttpGet.class);
	}

	/**
	 * 
	 * @return returns WsEstablishmentsHttpPost
	 */
	@WebEndpoint(name = "wsEstablishmentsHttpPost")
	public WsEstablishmentsHttpPost getWsEstablishmentsHttpPost() {
		return super.getPort(new QName("http://tempuri.org/",
				"wsEstablishmentsHttpPost"), WsEstablishmentsHttpPost.class);
	}

}
