package wsPanFinder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "wsEstablishmentsSoap", targetNamespace = "http://tempuri.org/")
public interface WsEstablishmentsSoap {

	/**
	 * 
	 * @param status
	 * @param establishment
	 * @param municipality
	 * @return returns wsPanFinder.ArrayOfOBJEstablishment
	 */
	@WebMethod(action = "http://tempuri.org/getEstablishments")
	@WebResult(name = "getEstablishmentsResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getEstablishments", targetNamespace = "http://tempuri.org/", className = "wsPanFinder.GetEstablishments")
	@ResponseWrapper(localName = "getEstablishmentsResponse", targetNamespace = "http://tempuri.org/", className = "wsPanFinder.GetEstablishmentsResponse")
	public ArrayOfOBJEstablishment getEstablishments(
			@WebParam(name = "status", targetNamespace = "http://tempuri.org/") String status,
			@WebParam(name = "establishment", targetNamespace = "http://tempuri.org/") String establishment,
			@WebParam(name = "municipality", targetNamespace = "http://tempuri.org/") String municipality);

}
